current:
    featured: testimonials

edition:
  date:
    start: "2015/07/18"
    end: "2015/07/20"
  to_html: "July 18<sup>th</sup> to 20<sup>th</sup> 2016"
  venue:
    id: venue_2016
  call_for_papers:
    deadline: "April 15th, 2016"

remaining:
  type: "Early Bird"
  count: 0